### ISSUE TITLE
大哥啊，你这代码样式和线上运行的样式，不一致啊

### ISSUE THREAD

**Issue by qingtian5266** [hxvin/airchat#13]
大哥啊，你这代码样式和线上运行的样式，不一致啊，就为了你这登录页面来的呢。。。结果样式根本就不对

**Comment by aermin** [comment]
> 大哥啊，你这代码样式和线上运行的样式，不一致啊，就为了你这登录页面来的呢。。。结果样式根本就不对

是的😂线上运行的是 https://github.com/aermin/ghChat 这个，也建议看线上运行的这个项目，vue-chat粗糙且几年没维护了
