### ISSUE TITLE
请教，为什么 `mysql`查出来的数据都要先 `JSON.parse(JSON.stringify(RowDataPacket))`

### ISSUE THREAD

**Issue by roy-lau** [hxvin/airchat#19]
为什么 `mysql`查出来的数据都要先 `JSON.parse(JSON.stringify(RowDataPacket))`

**Comment by vicksiyi** [comment]
因为可以将Mysql返回的数据强行转化为JSON格式

**Comment by roy-lau** [comment]
> 因为可以将Mysql返回的数据强行转化为JSON格式

MySQL返回的数据本来就是JSON格式的吧！

**Comment by vicksiyi** [comment]
> > 因为可以将Mysql返回的数据强行转化为JSON格式
> 
> MySQL返回的数据本来就是JSON格式的吧！

你可以看下，其实并不是JSON格式

**Comment by roy-lau** [comment]
> > > 因为可以将Mysql返回的数据强行转化为JSON格式
> 
> > 
> 
> > MySQL返回的数据本来就是JSON格式的吧！
> 
> 
> 
> 你可以看下，其实并不是JSON格式

的确如此，多谢！
